function response = send_detection_example()
% SEND_DETECTION_EXAMPLE
% Starter MATLAB function for sending a pest-detection result
% to the local CropSentinel dashboard backend.

endpoint = "http://localhost:8000/api/detections";

payload = struct( ...
    "pestName", "Aphid Cluster", ...
    "confidence", 0.84, ...
    "source", "MATLAB", ...
    "zone", "Leaf Cluster A", ...
    "boundingBox", struct( ...
        "x", 0.30, ...
        "y", 0.22, ...
        "width", 0.23, ...
        "height", 0.28 ...
    ), ...
    "fps", 24, ...
    "framesReviewed", 30 ...
);

options = weboptions( ...
    "MediaType", "application/json", ...
    "Timeout", 15 ...
);

response = webwrite(endpoint, payload, options);
disp(response);
end
